import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./app.css";
import { Header } from "./components";
import BottomNav from "./components/BottomNav";
import AuthGate from "./components/AuthGate";

const sans = Source_Sans_3({ subsets: ["latin"], weight: ["400","600","700"] });
sans.className = `${sans.className} pt-16`;

export const metadata: Metadata = {
  title: "NutriScan: Nutrition Facts Scanner",
  description:
    "Generated by Next.js, MongoDB, Browser Barcode Detection API, USDA and OpenFoodFacts APIs, Tailwind and hosted on Vercel",
  icons: "/nutrition-facts-scanner-logo.png",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <div className="min-h-screen pb-16">
          <Header />
          <AuthGate>
            <main className="p-4 bg-background-1">
              {children}
            </main>
          </AuthGate>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
